spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: hello-service
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 300m
            memory: 200Mi