spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: hello-service
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi